name: widgets
description: "A new Flutter package project."
version: 0.0.1
homepage: "none"

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:

